import { TailwindcssVarsInjectorConfig } from "./types";

export const defaultConfig: TailwindcssVarsInjectorConfig = {
  prefix: "tw",
  activeVars: [
    "screens",
    "colors",
    "spacing",
    "backgroundColor",
    "backgroundImage",
    "gradientColorStops",
    "borderColor",
    "borderRadius",
    "borderWidth",
    "boxShadow",
    "fontSize",
    "fontWeight",
    "height",
    "width",
    "minWidth",
    "minHeight",
    "maxWidth",
    "maxHeight",
    "padding",
    "margin",
    "space",
    "letterSpacing",
    "lineHeight",
    "listStyleType",
    "inset",
    "zIndex",
    "fill",
    "stroke",
    "fontFamily",
  ],
};
